-- both test users have the password 'password'

INSERT INTO users (username, password, first_name, last_name, email, bio, photo_url, portfolio_url, github_url, is_admin)
VALUES  ('wahmof2!',
        '$2b$12$ZKL5HIuLUd6U.zj0uKxj2Od5nKZbqJ0NPxQ7SPnVt12T7VSQOjlaq',
        'Andrea',
        'Martz',
        'hello@andreamartz.dev',
        'I am a full-stack web developer who used to work in professional certification testing. A self-starter and avid learner, I have worked 100% remotely for most of my career.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1627846993/capstone_connections/users_capstone_connections/lv6k2r59n9c9xeshkvhs_ktjgxt.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        TRUE),
        ('jweiss89',
        '$2b$12$ZYOJM/1WwVDFHDrdBqlJB.b4AthUimxNMc8yxOku72.AoSXjwIATW',
        'Jorge',
        'Weiss',
        'jorge.a.weiss@gmail.com',
        'Hello! My name is Jorge and I live in Chicago, IL. I have a bachelor''s degree in Biology from The University of Texas at Austin and studied Software Engineering at the school Springboard. At the moment, I''m working in United Airline''s Digital Technology Dept as part of their Early Career Digitial Leaership Program where I work with other developers, analysts, and security teams to continue to develop the best digital tools in the aviation industry.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628102043/capstone_connections/users_capstone_connections/Jorge-Weiss.jpg',
        'https://www.jorgeweiss.com/',
        'https://github.com/JAWeiss89',
        FALSE),
        ('awildstone',
        '$2b$12$JXEAVzHjybLmnrfpJAOkCOoRLWc3xmnq1CNZcCgwxIogQwWVoI56.',
        'Aimee',
        'Wildstone',
        'awildstone@gmail.com',
        'Hi! My name is Aimee Wildstone and I''m a Jr. Web Developer. I''m looking for a company in the Seattle area where I can bring a passion for delighting customers, solving problems, and building products for people.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628101940/capstone_connections/users_capstone_connections/Aimee-Wildstone.jpg',
        null,
        'https://github.com/awildstone',
        FALSE),
        ('Cerchie1',
        '$2b$12$/v1zIqMTq.Wkg9Yfmb36He3gHBJm8fJNcQRW/P55MVeoM1KbFsOtC',
        'Lucia',
        'Cerchie',
        null,
        null,
        'https://res.cloudinary.com/wahmof2/image/upload/v1627865381/capstone_connections/users_capstone_connections/imaqz8foelk8utcvexqu.png',
        'https://luciacerchie.dev/',
        null,
        FALSE),
        ('LuisSanc',
        '$2b$12$eJoW9gp7mft7ChXhh3RqnuI0Sm9o7eJhFqPWvEQo7tBIL0vyYSPXm',
        'Luis',
        'Sanchez',
        'galaxyplayeremail@gmail.com',
        'Food Service Manager turned Software Engineer.  Creating software solutions to problems is what drives me to improve every day.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1627911746/capstone_connections/users_capstone_connections/jurawafzwvzi4wrljpse.jpg',
        'https://luis-portfolio.vercel.app/',
        'https://github.com/lSanchez17/',
        FALSE),
        ('calendee',
        '$2b$12$72VrxeKKCgvk2O41yJ/Iou/AehyniOpRMjfN5uE/pKwZV71wEuEL.',
        'Justin',
        'Noel',
        'justin.noel@calendee.com',
        'In 2013, Justin Noel left his boring enterprise developer position in the telecom industry to jump into the exciting world of mobile app development. His own personal apps have not made him rich so, he’s been a contract mobile app developer for many years, just finished working as a React Native developer for a major e-commerce company in the fashion industry, and is now un(der)-employed and just enjoying dabbling with lots of new tech. Who knows what the future holds?',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628102084/capstone_connections/users_capstone_connections/justin-noel.png',
        'https://justinnoel.dev/',
        'https://github.com/calendee',
        FALSE),
        ('alexm323',
        '$2b$12$rPC.0r/.hRVEolWnOKU9.uLMduq9bMxw5hXyWLyFgqynU/kU5beGa',
        'Alejandro',
        'Martinez',
        'alejandromartinezjr42@gmail.com',
        'I thought my job as a Dealer was secure until the casinos in Los Angeles closed down due to the pandemic. I swore that day that I would never be in that position again and so I began my foray intro programming. I''m a member of the 100Devs team and a graduate of the Springboard Software Engineering Course. I am passionate about learning and building my skills and am currently learning about React Native and working on my first mobile app.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628102121/capstone_connections/users_capstone_connections/Alejandro-Martinez.jpg',
        'https://alexm323.github.io/portfolio/',
        'https://github.com/alexm323',
        FALSE),
        ('debrakayeelliott',
        '$2b$12$B68U4Fj6dV9Uks7IXezGC.Z8Xv5Cyhf1u0S76lazTJakULAOytJAu',
        'Debra-Kaye',
        'Elliott',
        'debrakayeelliott1@gmail.com',
        'I''m a Front End Developer, Graphic Designer and Blogger, self-learning web development. When I''m not down a tech rabbit hole or jumping around "all the things", I''m reading fiction novels, watching tv shows and movies.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628101995/capstone_connections/users_capstone_connections/Debra-Kaye-Elliott.jpg',
        'https://debrakayeelliott.com/',
        'https://github.com/debrakayeelliott',
        FALSE),
        ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test1',
        'User',
        'test1user@testuser.com',
        'I am testuser a self-taught web developer.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628100605/capstone_connections/users_capstone_connections/default-user-icon.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        FALSE),
        ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test2',
        'Admin',
        'test2user@testuser.com',
        'I am testadmin, a self-taught senior web developer.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628100605/capstone_connections/users_capstone_connections/default-user-icon.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        TRUE),
        ('user1',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'u1First',
        'u1Last',
        'user1@user1.com',
        'I am user1.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628100605/capstone_connections/users_capstone_connections/default-user-icon.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        FALSE),
        ('user2',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'u2First',
        'u2Last',
        'user2@user2.com',
        'I an user2.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628100605/capstone_connections/users_capstone_connections/default-user-icon.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        TRUE);


INSERT INTO projects (name, creator_id, image, repo_url, site_url, description, feedback_request)
VALUES  ('Access Academy',
        1,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628115339/capstone_connections/projects_capstone_connections/undraw_youtube_tutorial_2gn3-Access-Academy-Andrea-Martz.svg',
        'https://github.com/andreamartz/sb-29-capstone-1',
        'https://access-academy.herokuapp.com/',
        'Access Academy is a place where users can design courses for others or design their own learning path - by curating the most relevant videos from YouTube.',
        'This was the first full-stack project I had ever built. I did not know React or other frontend frameworks at the time, so it''s all done with JavaScript, which is challenging. When adding videos to a course, currently the process is clunky, and the user must add one video at a time, and redo the search for relevant videos each time. I''m curious to know if there is a slick way to fix this using pure JavaScript.'
        ),
        ('Ne-xo',
        2,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628102930/capstone_connections/projects_capstone_connections/ne-xo-mobile-view-en-Jorge-Weiss.png',
        'https://github.com/JAWeiss89/ne-xo',
        'https://ne-xo.herokuapp.com/',
        'A real-time chat application to facilitate communication between speakers of different languages.',
        'Looking to get feedback on the interface of the chat. Should users be able to customize the theme/colors? Also considering adding the ability for users to change font-size within the chat window but not sure if people would be interested in this. Any thoughts?'
        ),
        ('Water Mate',
        3,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628103099/capstone_connections/projects_capstone_connections/water-mate-Aimee-Wildstone.png',
        'https://github.com/awildstone/Water-Mate',
        'https://water-mate.herokuapp.com/',
        'Water Mate is a tool to help you organize your plant collection, keep track of the health of your plants, and help remind you when it''s time to water your plants. You have full control over how your collection is organized, so organize your collection in a way that makes sense for you!',
        null
        ),
        ('Personal Portfolio',
        4,
        'https://res.cloudinary.com/wahmof2/image/upload/v1626296156/capstone_connections/projects_capstone_connections/undraw_Website_builder_re_ii6e.svg',
        'https://github.com/Cerchie/portfolio-site',
        'https://luciacerchie.dev/',
        null,
        'Let me know how I can improve accessibility. I also have a CSS spacing bug on the projects section (scroll all the way to the right), would love pointers there!'
        ),
        ('Plant Keeper',
        5,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628103049/capstone_connections/projects_capstone_connections/plantKeeper-Luis-Sanchez.png',
        'https://github.com/lSanchez17/plant-keeper',
        'http://plant-keeper.herokuapp.com/',
        'An application to keep track of your plants.  Helps keep track of when to water, trim, and repot a plant.',
        'Ways to improve and expand my project!'
        ),
        ('Noel Voice',
        6,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628103013/capstone_connections/projects_capstone_connections/noel-voice-project-cover.jpg',
        null,
        'https://noelvoice.com/',
        'Website for Grainne Noel’s voice acting business.',
        E'* Design feedback would be appreciated. \n
        * An accessibility review would be great.'
        ),
        ('Carbe Diem',
        7,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628102881/capstone_connections/projects_capstone_connections/carbe_diem_landing-Alejandro-Martinez.jpg',
        'https://github.com/alexm323/carbe-diem',
        'https://github.com/alexm323/carbe-diem',
        'Calorie Tracker utilizing the Edamam API , Python-Flask, and JavaScript',
        'How might I improve the application and user flow'
        ),
        ('Coffee Heaven',
        8,
        'https://res.cloudinary.com/wahmof2/image/upload/v1626296156/capstone_connections/projects_capstone_connections/undraw_Website_builder_re_ii6e.svg',
        'https://github.com/debrakayeelliott/coffeeheaven',
        'https://coffeeheaven.netlify.app/',
        'A fun one-page website illustrating my love of coffee to help "learn by building" in dev speak.',
        E'1. How can I account for font choice not being available to everyone/have a choice other than default Arial that everyone can see? \n2. How can I make my site more response without a bunch of complexities?'
        );


INSERT INTO tags (text)
VALUES ('HTML'),
        ('CSS'),
        ('JS'),
        ('API');

INSERT INTO projects_tags (project_id, tag_id)
VALUES  (1, 1),
        (1, 2),
        (1, 3),
        (1, 4),
        (2, 3),
        (2, 4),
        (3, 4),
        (4, 1),
        (4, 2),
        (4, 3),
        (5, 1),
        (5, 2),
        (5, 3),
        (5, 4),
        (6, 1),
        (6, 2),
        (7, 1),
        (7, 2),
        (7, 3),
        (7, 4),
        (8, 1),
        (8, 2);