-- both test users have the password "password"

INSERT INTO users (username, password, first_name, last_name, email, bio, photo_url, portfolio_url, github_url, is_admin)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test1',
        'User',
        'test1user@testuser.com',
        'I am testuser a self-taught web developer.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628100605/capstone_connections/users_capstone_connections/default-user-icon.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        FALSE
        ),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test2',
        'Admin',
        'test2user@testuser.com',
        'I am testadmin, a self-taught senior web developer.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628100605/capstone_connections/users_capstone_connections/default-user-icon.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        TRUE),
        ('user1',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'u1First',
        'u1Last',
        'user1@user1.com',
        'I am user1.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628100605/capstone_connections/users_capstone_connections/default-user-icon.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        FALSE),
        ('user2',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'u2First',
        'u2Last',
        'user2@user2.com',
        'I an user2.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628100605/capstone_connections/users_capstone_connections/default-user-icon.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        TRUE),
        ('wahmof2',
        '',
        'Andrea',
        'Martz',
        'hello@andreamartz.dev',
        'I am a full-stack web developer who used to work in professional certification testing. A self-starter and avid learner, I have worked 100% remotely for most of my career.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1627846993/capstone_connections/users_capstone_connections/lv6k2r59n9c9xeshkvhs_ktjgxt.png',
        'https://andreamartz.dev/',
        'https://github.com/andreamartz',
        TRUE),
        ('jweiss89',
        '$2b$12$ZYOJM/1WwVDFHDrdBqlJB.b4AthUimxNMc8yxOku72.AoSXjwIATW',
        'Jorge',
        'Weiss',
        'jorge.a.weiss@gmail.com',
        `Hello! My name is Jorge and I live in Chicago, IL. I have a bachelor's degree in Biology from The University of Texas at Austin and studied Software Engineering at the school Springboard. At the moment, I'm working in United Airline's Digital Technology Dept as part of their Early Career Digitial Leaership Program where I work with other developers, analysts, and security teams to continue to develop the best digital tools in the aviation industry.`,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628102043/capstone_connections/users_capstone_connections/Jorge-Weiss.jpg',
        'https://www.jorgeweiss.com/',
        'https://github.com/JAWeiss89',
        FALSE
        ),
        ('awildstone',
        '$2b$12$JXEAVzHjybLmnrfpJAOkCOoRLWc3xmnq1CNZcCgwxIogQwWVoI56.',
        'Aimee',
        'Wildstone',
        'awildstone@gmail.com',
        `Hi! My name is Aimee Wildstone and I'm a Jr. Web Developer. I’m looking for a company in the Seattle area where I can bring a passion for delighting customers, solving problems, and building products for people.`,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628101940/capstone_connections/users_capstone_connections/Aimee-Wildstone.jpg',
        null,
        'https://github.com/awildstone',
        FALSE
        ),
        ('Cerchie1',
        '$2b$12$/v1zIqMTq.Wkg9Yfmb36He3gHBJm8fJNcQRW/P55MVeoM1KbFsOtC',
        'Lucia',
        'Cerchie',
        null,
        null,
        'https://res.cloudinary.com/wahmof2/image/upload/v1627865381/capstone_connections/users_capstone_connections/imaqz8foelk8utcvexqu.png',
        'https://luciacerchie.dev/',
        null,
        FALSE
        ),
        ('LuisSanc',
        '$2b$12$eJoW9gp7mft7ChXhh3RqnuI0Sm9o7eJhFqPWvEQo7tBIL0vyYSPXm',
        'Luis',
        'Sanchez',
        'galaxyplayeremail@gmail.com',
        'Food Service Manager turned Software Engineer.  Creating software solutions to problems is what drives me to improve every day.',
        'https://res.cloudinary.com/wahmof2/image/upload/v1627911746/capstone_connections/users_capstone_connections/jurawafzwvzi4wrljpse.jpg',
        'https://luis-portfolio.vercel.app/',
        'https://github.com/lSanchez17/',
        FALSE
        ),
        ('calendee',
        '$2b$12$72VrxeKKCgvk2O41yJ/Iou/AehyniOpRMjfN5uE/pKwZV71wEuEL.',
        'Justin',
        'Noel',
        'justin.noel@calendee.com',
        'In 2013, Justin Noel left his boring enterprise developer position in the telecom industry to jump into the exciting world of mobile app development. His own personal apps have not made him rich so, he’s been a contract mobile app developer for many years, just finished working as a React Native developer for a major e-commerce company in the fashion industry, and is now un(der)-employed and just enjoying dabbling with lots of new tech. Who knows what the future holds?',
        'https://res.cloudinary.com/wahmof2/image/upload/v1628102084/capstone_connections/users_capstone_connections/justin-noel.png',
        'https://justinnoel.dev/',
        'https://github.com/calendee',
        FALSE
        ),
        ('alexm323',
        '$2b$12$rPC.0r/.hRVEolWnOKU9.uLMduq9bMxw5hXyWLyFgqynU/kU5beGa',
        'Alejandro',
        'Martinez',
        'alejandromartinezjr42@gmail.com',
        `I thought my job as a Dealer was secure until the casinos in Los Angeles closed down due to the pandemic. I swore that day that I would never be in that position again and so I began my foray intro programming. I'm a member of the 100Devs team and a graduate of the Springboard Software Engineering Course. I am passionate about learning and building my skills and am currently learning about React Native and working on my first mobile app.`,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628102121/capstone_connections/users_capstone_connections/Alejandro-Martinez.jpg',
        'https://alexm323.github.io/portfolio/',
        'https://github.com/alexm323',
        FALSE
        ),
        ('debrakayeelliott',
        '$2b$12$B68U4Fj6dV9Uks7IXezGC.Z8Xv5Cyhf1u0S76lazTJakULAOytJAu',
        'Debra-Kaye',
        'Elliott',
        'debrakayeelliott1@gmail.com',
        `I'm a Front End Developer, Graphic Designer and Blogger, self-learning web development. When I'm not down a tech rabbit hole or jumping around "all the things", I'm reading fiction novels, watching tv shows and movies.`,
        'https://res.cloudinary.com/wahmof2/image/upload/v1628101995/capstone_connections/users_capstone_connections/Debra-Kaye-Elliott.jpg',
        'https://debrakayeelliott.com/',
        'https://github.com/debrakayeelliott',
        FALSE
        );


INSERT INTO projects (name, creator_id, image, repo_url, site_url, description, feedback_request)
VALUES ('This is Test Project #1 - One Layover',
        1,
        'https://placekitten.com/200/300',
        'https://github.com/JAWeiss89/onelayover',
        'https://www.onelayover.com/',
        'A place for flight attendants to share layover info',
        'Please give feedback on frontend and backend. Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto nam reiciendis facere quasi magni iste corporis at placeat ipsam sequi in, voluptas repellendus, recusandae '),
       ('This is Test Project #2 - Access Academy',
        2,
        'https://placem.at/things?w=300&random=1',
        'https://github.com/andreamartz/sb-29-capstone-1',
        'https://access-academy.herokuapp.com/',
        'Course creation site for free self-teaching',
        'Is there a better way to organize my CSS? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto nam reiciendis facere quasi magni iste corporis at placeat ipsam sequi in, voluptas repellendus, recusandae inventore ratione rerum eaque! Atque earum repellendus nostrum perferendis natus ipsa hic sequi cupiditate quo perspiciatis laboriosam incidunt facilis, laudantium corrupti fugiat voluptatibus et excepturi! Porro illum ullam reiciendis impedit ab quisquam fuga, omnis soluta veniam odit ipsum odio corrupti optio quis neque! Provident nesciunt doloremque iste voluptatum voluptas! Distinctio, voluptatibus sequi qui ratione quam iusto esse dicta sunt! Quod magnam, corrupti, illo perferendis velit dolorem voluptates nam ratione molestiae eaque amet optio tenetur temporibus minima.'),
       ('This is Test Project #3 - Jobly',
        3,
        'https://placekitten.com/200/300',
        'https://github.com/andreamartz/sb-43-React-Jobly-frontend',
        'https://jobs-app.surge.sh/',
        'Jobs and Companies',
        'Is there a better way to organize my CSS? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto nam reiciendis facere quasi magni iste corporis at placeat ipsam sequi in, voluptas repellendus, recusandae inventore ratione rerum eaque! Atque earum repellendus nostrum '),
       ('This is Test Project #4 - Allytweetfrontend',
        4,
        'https://placekitten.com/200/300',
        'https://github.com/Cerchie/a11ytweetfrontend/tree/main/src',
        'https://luciacerchie.dev/',
        'A11y Retweet Bot',
        'Atque earum repellendus nostrum perferendis natus ipsa hic sequi cupiditate quo perspiciatis laboriosam incidunt facilis, laudantium corrupti fugiat voluptatibus et excepturi! Porro illum ullam reiciendis impedit ab quisquam fuga, omnis soluta veniam odit ipsum odio corrupti optio quis neque! Provident nesciunt doloremque iste voluptatum voluptas! Distinctio, voluptatibus sequi qui ratione quam iusto esse dicta sunt! Quod magnam, corrupti, illo perferendis velit dolorem voluptates nam ratione molestiae eaque amet optio tenetur temporibus minima.'),
        ('This is Test Project #5 - My Minimony',
        2,
        'https://placekitten.com/200/300',
        'https://github.com/agiletkiewicz/my-minimony-frontend',
        'https://www.myminimonyapp.com/',
        'My Minimony',
        'Distinctio, voluptatibus sequi qui ratione quam iusto esse dicta sunt!'
        );


INSERT INTO tags (text)
VALUES ('HTML'),
        ('CSS'),
        ('JS'),
        ('API');


INSERT INTO projects_tags (project_id, tag_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (2, 3),
       (2, 4),
       (3, 2),
       (4, 1),
       (4, 2),
       (4, 3),
       (4, 4);

INSERT INTO project_likes (liker_id, project_id)
VALUES (1, 2),
       (1, 3),
       (2, 3),
       (3, 1),
       (4, 2),
       (4, 3);

INSERT INTO project_comments (commenter_id, project_id, comment)
VALUES (
        1, 2, 'Your whole project is just great! Atque earum repellendus nostrum perferendis natus ipsa hic sequi cupiditate quo perspiciatis laboriosam incidunt facilis'),
       (2, 1, 'Nice use of code!'),
       (3, 1, 'Hey, great job! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto nam reiciendis facere quasi magni iste corporis at placeat ipsam sequi in, voluptas repellendus, recusandae inventore ratione rerum eaque! Atque earum repellendus nostrum '),
       (3, 2, 'Way to go! Lorem ipsum dolor sit amet consectetur adipisicing elit.'
);

INSERT INTO project_comment_likes (liker_id, comment_id)
VALUES (2, 1),
       (2, 2),
       (2, 4),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4);